vubiostat/redcapAPI

R/validateImport_methods.R, tests/testthat/test-validateImport_methods.R
There is a touch of scope creep in here. I was writing tests on all of the validations to see if we had any other noise coming. In a few instances, I found places where the validations weren't work as I would expect or intend (itemized below)
I did not write tests for the checkbox validation. I will do that under #18 
Some observations I made but elected not to do anything with are
1. when validating times, should a leading zero be optional?  (i.e. is 6:15 acceptable). 
2. with times, it is only looking at two digits. Not all digits are acceptable. Should we be limiting these to valid times? (0-24:0-60:0-60) As it stands, we would recognize 31:72:89 as a valid time.
3. yes/no only accepts no, yes, 0, and 1. Should it also permit TRUE/FALSE? (for comparison, the validation for truefalse …
=> Issue17 import warning

R/importRecords.R, R/validateImport_methods.R, man/importRecords.Rd, tests/testthat/test-validateImport_methods.R
Tests for validation of checkboxes. Minor fixes to validate_import_checkbox to bring it into compliance with expectations definedin tests.
Writing the tests exposed some weaknesses in the validation which have been corrected.
Note that the validate_import_methods file and its accompanying test file are also modified in pull request #19
=> documentation and tests

R/checkbox_suffixes.R, tests/testthat.R, tests/testthat/helper-REDCapQACredentials.R, tests/testthat/test-checkbox_suffixes.R, tests/testthat/test-exportArms.R, tests/testthat/test-exportEvents.R, tests/testthat/test-exportFieldNames.R, tests/testthat/test-exportInstruments.R, tests/testthat/test-exportMappings.R, tests/testthat/test-exportMetaData.R, tests/testthat/test-exportNextRecordName.R, tests/testthat/test-exportProjectInformation.R, tests/testthat/test-exportRecords.R, tests/testthat/test-exportUsers.R, tests/testthat/test-exportVersion.R
It's unsolicited, but you didn't tell me "no" :) 
I haven't worked on exportBundle, exportFiles, exportPdf, exportRecords_offline, or exportRecords.
In most cases, I figured it would be better to write those tests after making a space in the test project to test those features.
There is one file modified that isn't a testing file. While writing tests for checkbox_suffix, I found some flaws in how the checkbox labels were being extracted.  I felt the change was small enough to warrant slipping in.
=> Tests for most of the remaining export functions

R/exportRecords.R, R/exportRecords_offline.R, R/exportReports.R, R/fieldToVar.R, man/exportRecords.Rd, man/exportReports.Rd, tests/testthat/test-exportRecords.R
- add drop= argument to exportRecords that takes a character vector E.g. `drop=c("field_name_one", "field_name_2") and does not return the fields listed
- add drop= to exportRecords_offline
- Create test case for drop argument
=> Bstatgen 1094 drop arg

R/exportRecordsTyped.R
Per an external communication, this will validate the `fields`, `drop_fields`, `forms`, and `events` all request values that exist in the project.
=> validate user provided fields and forms against REDCap

DESCRIPTION, R/makeApiCall.R, R/redcapConnection.R, man/fieldChoiceMapping.Rd, man/makeApiCall.Rd, man/redcapConnection.Rd, tests/testthat/test-makeApiCall.R, tests/testthat/test-redcapConnection.R
`redcapConnection` gains the following arguments
* retries - determines how many attempts to make at the API call if there is a time out error.
* retry_interval - how long to wait before attempts. Defaults to 2^(1:5), (2, 4, 8, 16, 32). It isn't quite what you described in the issue description, but it was similar, easy to implement, and easy to modify by the user.
* retry_quietly - if FALSE, messages about the retry attempts will be displayed. I suspect these may be useful in future debugging efforts. Defaults to TRUE.
`redcapConnection` also gains methods to extract and set those values (ie `rcon$retries()` and `rcon$set_retries(4)`. 
`makeApiCall` utilizes the values from the redcapConnection in a loop with `retries` iterations and the following behaviors
1. If the returns a code of …
=> Add timeout strategy

R/importRecords.R, man/importRecords.Rd, tests/testthat/test-11-records-argValidation.R, tests/testthat/test-11-records-importRecords.R
Address #72 : any fields found in the data being imported that do not match an importable fields are removed with a message.
Also addresses https://github.com/nutterb/redcapAPI/issues/29 by providing arguments to access auto numbering. 
Tests are added for each of these changes.
=> Issue 72 import records

tests/testthat/test-08-logging.R
Addresses #79 
I also ran the following to confirm it works with all records current in the logging. 
```
Records <- FullLog[!is.na(FullLog$record) & !grepl("user", FullLog$action), ]
records <- FullLog$record
records <- trimws(records)
records <- unique(records)
for (i in seq_along(records)){
record_for_test <- records[i]
Logs <- exportLogging(rcon, 
record = record_for_test)
all_record <- all(Logs$record %in% c(record_for_test, NA))
print(all_record)
}
```
=> test Logs allows NA in records logs

R/exportRecordsTyped.R, tests/testthat/test-11-recordsTyped-exportRecordsTyped.R, tests/testthat/test-11-recordsTyped-exportRecordsTypedOffline.R
Implements and adds tests for the following use cases:
1. User requests no fields (fields = NULL); receives all fields (actual + system)
2. User requests actual fields; receives requested fields + system fields
3. User requests actual fields + system_fields; user receives only the requested fields from both
4. User requests only system_fields; user receives only the requested system fields
Caveat: I think this will work when DAGs get involved, but we haven't implemented that yet, so I have been unable to test. When we get into repeated instruments, we'll want to revisit these tests.  I've left FIXME: notes in those tests.
=> 102 fail on system field

R/importRecords.R
This is a bit risky; I haven't incorporated tests into the test suite because
* the redcap_data_access_group column gets added to a lot of calls and kind of blows up the test suite. 
* we don't have a programmatic way to add/remove DAGs, and I'm not prepared to adapt the test suite to a single DAG just yet.
I did run this code against the project listed as Basic Data Types (For Testing) (project_id = 167805)
```
> exportRecordsTyped(basic_data, fields = "record_id")
record_id redcap_data_access_group
1         1                     <NA>
> 
> NewData <- data.frame(record_id = 1, 
+                       redcap_data_access_group = 'cute_dag_name')
> 
> importRecords(basic_data, NewData, overwriteBehavior = "overwrite")
The variable(s) 'calc_addition', 'calc_squared' are calculated fields …
```
=> Import DAGs

tests/testthat/test-splitForms.R
quiet the warning message generated from the test-splitForms exportRecordsTyped call
=> quiet warning message in test

R/fieldCastingFunctions.R, tests/testthat/test-11-records-mChoice.R
Add a drop_fields argument to mChoice fields that defaults to TRUE and drops the component/suffixed checkbox field names.
When drop_fields = FALSE remove the suffixed field names from the data returned.
Closes #159
=> Issue 159 m choice cast

NEWS, R/zzz.R, tests/testthat/test-00-packageSetup.R, tests/testthat/test-unlockREDCap.R
* Sets the default timeout to 5 minutes
* If a setting was made prior to loading the package, it will revert to that prior setting
* Tests provided that confirm the timeout can be overridden on either the connection object or the function call
This doesn't use the proposed `modifyList` strategy. Instead it uses the httr workflow. (the workflow itself is awkward, because you have to make a change in order to determine if something existed before, but we'd have to do that with the `modifyList` strategy anyway).
=> Set up default timeout

R/exportRecordsTyped.R, R/fieldCastingFunctions.R, R/fieldValidationAndCasting.R, R/purgeRestoreProject.R, R/redcapConnection.R, man/exportRecordsTyped.Rd, man/fieldValidationAndCasting.Rd, man/redcapConnection.Rd, tests/testthat/test-11-records-deleteRecords.R, tests/testthat/test-11-records-importRecords.R, tests/testthat/test-11-recordsTyped-exportRecordsTyped.R, tests/testthat/test-11-recordsTyped-exportRecordsTypedOffline.R, tests/testthat/test-prepUserImportData.R
* Adds a "system" field type that casts `redcap_event_name`, `redcap_repeat_instrument` and `redcap_data_access_group`
* Maps the coded and labeled values for these fields into a code book to make them respond to castLabel and castRaw
* Adds dags to the redcapOfflineConnection
* Modifies tests to pass with the new system field casting
=> 171 label event dag

R/importUserRoleAssignments.R, R/importUserRoles.R, R/importUsers.R, man/importUsers.Rd, tests/testthat/test-103-userRoleAssignmentMethods-Functionality.R
Automates updating user rights when a user is actively assigned a user role.  This is accomplished by
* Storing the user role assignment
* Remove the user role assignment
* Applying the user rights via importUsers
* Restore the role assignment
Description of this is added to the documentation with clarification that changes to user rights assigned via roles preempt rights assigned to the user.
=> Issue 206 import user assigned to role

R/validateImport.R, R/validateImport_methods.R, tests/testthat/test-109-instrumentMethods-Functionality.R, tests/testthat/test-200-exportTypedRecords-Functionality.R, tests/testthat/test-201-exportTypedRecords-withDAGs.R, tests/testthat/test-204-exportTypedRecords-withRepeatingInstruments.R, tests/testthat/test-903-validateImport_methods.R
validates imports for number_1dp, number_2dp, number_1dp_comma_decimal, and number_2dp_comma_decimal. 
Tests added for validate_import_methods with these new methods. 
Resolves Issue #217
=> validate imports for fixed decimal place numbers (and tests)

NEWS, R/exportFiles.R, tests/testthat/test-301-fileMethods-Functionality.R
Addresses #245 
* Implements repeat_instance in the API call of exportFiles.
* Adds tests to explicitly test that files can be imported, exported, and deleted from repeat instances greater than 1.
* NEWS updated
Check passes with no warnings, notes, or errors.
All tests passing.
=> implement repeat_instance in exportFiles

R/exportRecordsTyped.R
Very simple warning. I didn't add a test case as this is just a nudge to not simply replace exportRecords with exportRecordsTyped.
=> Issue #254

R/constructLinkToRedcapForm.R
Remove the need for a form_name on record link construction.
=> strip form_name check

R/fieldCastingFunctions.R, tests/testthat/test-200-exportTypedRecords-Functionality.R
Addresses #301 
Checkbox field labels take the form `[Field Label] (choice=[Choice Label])`
Will also be useful in getting #285 up to standard.
Should also help with #299
=> detailed field labels for checkbox fields. 

R/assembleCodebook.R, tests/testthat/test-258-assembleCodebook.R
This adds the `redcap_repeat_instance`. It carries the same field attributes as a numeric field. 
I did not end up adding tests.  All of the tests I wanted to add were related to the missing data codes. Unfortunately, those can't be added through the API, so there's no way to automate the testing.  My internal testing indicates it is working.
=> Issue 285 codebook improvement

DESCRIPTION, NEWS, R/createFileRepositoryFolder.R, R/exportArms.R, R/exportDags.R, R/exportEvents.R, R/exportFieldNames.R, R/exportInstruments.R, R/exportLogging.R, R/exportMappings.R, R/exportProjectInformation.R, R/exportRecordsTyped.R, R/exportRepeatingInstrumentsEvents.R, R/exportReports.R, R/exportReportsTyped.R, R/exportUserDagAssignments.R, R/exportUserRoleAssignments.R, R/exportUserRoles.R, R/exportUsers.R, R/importRecords.R, R/makeApiCall.R, tests/testthat/test-050-makeApiCall.R
In the interest of slaying these bugs, I've prepped this pull request for discussion.
Questions I have:
1) Should we have a warning, or is just \u25a1 substitution sufficient?
2) Would an API reply ever be something besides UTF-8, i.e. should we use the content in the header to define the target encoding?
=> Iconv 290 297 314

tests/testthat/helper-00-REDCapQACredentials.R
This should stop the test with a clear message. Also, added some instructions on switching projects easily.
=> Tests stop if missing codes are defined. #350

NEWS, R/fieldCastingFunctions.R
assign form_complete field type to fields where the form name followed by _complete is found
=> Correctly assign form_complete field types

README.md
Hi team,
I’ve added a new badge to the README file to display the status of the GitHub Action for R CMD check. This badge will help us quickly see the build status and ensure our code passes the necessary checks.
=> add badge to README

NEWS, tests/testthat/test-024-unlockREDCap.R
- Ensure the CI tests that the user interface is called twice:
- Once for the keyring password
- Once for the token
- Ensure the local test only calls the user interface once, as the keyring is already unlocked during the test script run
=> feat: Add CI test for user interface calls

DESCRIPTION, NEWS, R/docsRecordsManagementMethods.R, R/exportFieldNames.R, R/renameRecord.R, R/unlockREDCap.R, man/exportFieldNames.Rd, man/recordsManagementMethods.Rd, tests/testthat/test-108-metadataMethods-Functionality.R, tests/testthat/test-358-renameRecord-ArgumentValidation.R, tests/testthat/test-358-renameRecord-Functionality.R
* vectorizes `renameRecord` and `exportFieldNames`
* Adds tests for vectorized forms
`renameRecord` requires that the arguments `record_name` and `new_record` name be the same length. It `arms` is not `NULL` it must also be the same length. 
`renameRecord` returns a vector of `TRUE/FALSE`. it is unnamed, but gives an indication of which calls succeeded or failed.
`exportFieldNames` returns a data frame, as is always has.
=> Issue 389 vectorize renameRecord and exportFieldNames

R/unlockREDCap.R
`osVersion` can be `NULL` (`?osVersion`). That would break the `if()` check (`if (logical())`). This `isTRUE()` wrapper is the simplest fix.
=> robust to NULL osVersion
