tests/testthat/test-exportReports.R
- add test case for exporting reports with and without drop
=> add reports export tests

R/exportRecords.R
For consideration to address test that have started to fail and Issue #59 
Note: I haven't run `check`. I can't seem to get all of the packages I need to set up the environment on this machine.
=> implement vectorToApiBodyList in exportRecords

R/exportRecordsTyped.R
I haven't gotten to all of them yet, but there are a few ideas to consider in here.
=> some suggestions

R/exportRecordsTyped.R
I had assumed if fields = NULL, we would include all fields.  That assumption should be fields == NULL AND forms == NULL. 
I've fixed that and all your tests pass now.
=> Change assumption on default inclusion of fields

R/exportRecordsTyped.R, tests/testthat/test-11-recordsTyped-exportRecordsTyped.R
Add a codebook for yes/no fields. Also adds a test to confirm it processes correctly
=> Issue #83 - yesno fields in exportRecordsTyped

R/fieldCastingFunctions.R, tests/testthat/test-castForImport.R
=> honor fields argument of recastForImport

R/unlockREDCap.R, man/unlockREDCap.Rd
I went ahead and did this in hopes it prevents further abuse of the config argument.
=> Issue #124. Removed config from unlockREDCap

R/importRecords.R
=> Removing extraneous import message #128

R/fieldValidationAndCasting.R
valChoice function does not work for choices with embedded fields. Update the valChoice function to allow {} from other fields
=> update valChoice to work with embedded options

NEWS, R/exportRecordsTyped.R, R/missingSummary.R, R/splitForms.R, R/unlockREDCap.R, README.md, man/exportBulkRecords.Rd, man/missingSummary.Rd, man/splitForms.Rd, man/unlockREDCap.Rd, tests/testthat/test-11-records-exportBulkRecords.R, tests/testthat/test-splitForms.R
Here's the envir handling suggestions from Cole.
Additionally:
* Fixed incompatible post handling between `exportBulkRecords` and `splitRecords`
* Fixed documentation link to deleted doc.
=> Issue 149 envir

R/exportRecordsTyped.R, tests/testthat/test-11-recordsTyped-exportRecordsTyped.R
Implements the same strategy for error handling used in other API wrappers
=> 146 error handling

DESCRIPTION, R/unlockREDCap.R, man/unlockREDCap.Rd
Take 2. User confirmed this works.
=> Issue 134 revisited

NEWS, R/exportRecordsTyped.R, man/exportRecordsTyped.Rd, tests/testthat/test-11-recordsTyped-arg-validation.R, tests/testthat/test-11-recordsTyped-exportRecordsTyped.R
=> Added filter_empty_rows flag to exportRecordsTyped #200

NEWS, tests/testthat/test-024-unlockREDCap.R
Created this hoping it addresses the issues that were seen.
=> Removed deprecated mock #238

R/docsRecordsTypedMethods.R, R/documentation-common-args.R, man/fieldCastingFunctions.Rd, man/recordsTypedMethods.Rd
Adds documentation about system fields and how to change from labelled to raw values.
=> Add statement about system fields

R/redcapDataStructure.R
This fixes 357 breakage for 14.0.3
=> Version 14.0.3 structure change. #288

tests/testthat/test-002-projectSetup.R
This helped me triaging the log issue. Works better as tests.
=> Turned project setup 002 into tests.

NEWS, R/filterEmptyRow.R
=> improve speed filterEmptyRow function

R/docsRecordsTypedMethods.R, R/exportRecordsTyped.R, R/exportReportsTyped.R, R/fieldCastingFunctions.R, R/isZeroCodedCheckField.R, man/fieldCastingFunctions.Rd, man/isZeroCodedCheckField.Rd, man/recordsTypedMethods.Rd, tests/testthat/test-059-isZeroCodedCheckField.R
I think I got all the cases. There's a lot of paths through this one.
=> Issue zero warn 235

R/exportFileRepositoryListing.R, R/exportMetaData.R, R/exportRecords.R, R/exportSurveyParticipants.R
Missed some cases. There is one thing to consider on this, the drop_utf8 flag is probably no longer needed. Should I just strip that out?
=> Previous patch missed some cases, #290 #297 #314

R/exportEvents.R, R/exportRecordsTyped.R, R/exportUserDagAssignments.R, R/exportUserRoleAssignments.R, R/exportUserRoles.R, R/makeApiCall.R, R/purgeRestoreProject.R, README.md, tests/testthat/test-201-exportTypedRecords-withDAGs.R
This is yet another evolution in the difficulty of encoding issues. Test cases are proving HIGHLY useful in getting this working properly. 
── R CMD check results ──────────────────────── redcapAPI 2.8.4 ────
Duration: 40.4s
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
R CMD check succeeded
── Skipped tests (9) ───────────────────────────────────────────────
• Tests to be developed for 3.0.0 release (9):
test-151-exportRecords-ArgumentValidation.R:6:5,
test-151-exportRecords-Functionality.R:6:5,
test-152-exportRecordsWithDags.R:6:5,
test-153-exportRecordsWithEvents.R:6:5,
test-155-exportRecordsWithRepeatingInstruments.R:6:5,
test-180-exportRecordsOffline-ArgumentValidation.R:6:5,
test-180-exportRecordsOffline-Functionality.R:6:5,
test-190-exportReports-ArgumentValidation.R:6:5, …
=> Iconv 290 297 314 Yet more missed cases

R/documentation-common-args.R, R/makeApiCall.R, man/fieldCastingFunctions.Rd, man/recordsTypedMethods.Rd
Had to make changes to pass win-builder on devel
=> Changes required by win-builder devel #318

DESCRIPTION, NEWS, R/filterEmptyRow.R
For large datasets, this shaves about 7% off export times. Untested.
=> #326 optimize export via filterEmptyRow changes

NEWS, R/deleteRecords.R, man/deleteRecords.Rd, tests/testthat/test-150-importDeleteRecords-ArgumentValidation.R
Knocking out these additional arguments for #315
=> Delete rec arg 315

NEWS, R/docsRecordsTypedMethods.R, R/exportRecordsTyped.R, man/recordsTypedMethods.Rd, man/redcapAPI.Rd, tests/testthat/test-204-exportTypedRecords-withRepeatingInstruments.R, tests/testthat/test-240-exportTypedReports-Functionality.R, tests/testthat/test-250-recastRecords.R, tests/testthat/test-356-missingSummary.R
Issue #365 
Set default dag argument to FALSE
=> set default dag arg to false

NEWS, R/exportExternalCoding.R, R/exportRecordsTyped.R
Issue #364 
Metadata is corrupted on export. Adding a patch to ignore NA field type
=> Issue 364 lost bioportal field

DESCRIPTION, NEWS, R/docsRecordsTypedMethods.R, R/redcapDataStructure.R, man/recordsTypedMethods.Rd, man/redcapDataStructures.Rd, tests/testthat/test-204-exportTypedRecords-withRepeatingInstruments.R, tests/testthat/test-205-exportTypedRecords-offline-Functionality.R
#355 
Add `redcap_survey_identifier` to system fields. 
[ FAIL 0 | WARN 0 | SKIP 13 | PASS 2133 ]
=> add redcap_survey_identifier to system fields

R/importMetaData.R, tests/testthat/test-800-exportLogging-Functionality.R
Fixing importMetaData validations.
=> Loosen import meta data val 381

.Rbuildignore, .github/workflows/r-cmd-check.yml, NEWS
This pull request introduces significant updates to the RedcapAPI integration, including the addition of a comprehensive R-CMD-check workflow. Resolves #398
=> Enhancements to REDCap API Integration 
